name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: .NET Build
      run: dotnet build Andromeda.Expressions.sln -c Release
      
    - name: .NET Test
      run: dotnet test Andromeda.Expressions.sln -c Release --no-build

    - name: Push Andromeda.Expressions
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet nuget push Andromeda.Expressions.*.*.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
    
    - name: Push Andromeda.FastExpressions
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet nuget push Andromeda.FastExpressions.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate